apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msrt-bot.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "msrt-bot.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.bot.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.bot.logLevel | quote }}
  {{- range .Values.extraEnvVars }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}