apiVersion: v1
kind: Service
metadata:
    name: { { include "msrt-bot.fullname" . } }
    namespace: { { .Release.Namespace } }
    labels: { { - include "msrt-bot.labels" . | nindent 4 } }
spec:
    type: { { .Values.service.type } }
    ports:
        - port: { { .Values.service.port } }
          targetPort: { { .Values.service.targetPort } }
          protocol: TCP
          name: http
    selector: { { - include "msrt-bot.selectorLabels" . | nindent 4 } }
